name       : kdepim-addons
version    : 22.12.1
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/kdepim-addons-22.12.1.tar.xz : 1315ecc4339f01c39e9c9fe249d53844faf88896b45952d70c0a518f8445baff
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Addons for KDE PIM applications
description: |
    Addons for KDE PIM applications including akregator, kaddressbook, kmail and korganizer.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(libmarkdown)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-import-wizard-devel
    - akonadi-notes-devel
    - calendarsupport-devel
    - eventviews-devel
    - incidenceeditor-devel
    - kaddressbook-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kguiaddons-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitinerary-devel
    - kmailtransport-devel
    - kontactinterface-devel
    - kparts-devel
    - kpkpass-devel
    - ktnef-devel
    - libgravatar-devel
    - libksieve-devel
    - mailcommon-devel
    - mailimporter-devel
    - pimcommon-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
