name       : kdepim-addons
version    : 20.04.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kdepim-addons-20.04.0.tar.xz : ec22ecda33cf1f7b29856d08aa0c9bf65135775f624bd895c838c4cac2f796b2
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Addons for KDE PIM applications
description: |
    Addons for KDE PIM applications including akregator, kaddressbook, kmail and korganizer.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(libmarkdown)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-import-wizard-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - calendarsupport-devel
    - eventviews-devel
    - extra-cmake-modules
    - gpgme-devel
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - incidenceeditor-devel
    - karchive-devel
    - kcalutils-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdepim-apps-libs-devel
    - kholidays-devel
    - khtml-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kitinerary-devel
    - kmailtransport-devel
    - kmime-devel
    - kontactinterface-devel
    - kpimtextedit-devel
    - kpkpass-devel
    - ktnef-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libgravatar-devel
    - libkdepim-devel
    - libkleo-devel
    - libksieve-devel
    - mailcommon-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - prison-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
