name       : kdepim-addons
version    : 18.08.1
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kdepim-addons-18.08.1.tar.xz : f265a957db6f09ec98aaa24e7c5dd2a4782a5fcf4a4aa220071e13da007eef39
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Addons for KDE PIM applications
description: |
    Addons for KDE PIM applications including akregator, kaddressbook, kmail and korganizer.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5WebEngine)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-import-wizard-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - calendarsupport-devel
    - eventviews-devel
    - extra-cmake-modules
    - gpgme-devel
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - incidenceeditor-devel
    - karchive-devel
    - kcalcore-devel
    - kcalutils-devel
    - kconfig-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdepim-apps-libs-devel
    - kholidays-devel
    - khtml-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - ki18n-devel
    - kimap-devel
    - kitemmodels-devel
    - kitinerary-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - kpkpass-devel
    - ktnef-devel
    - kwallet-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libgravatar-devel
    - libkdepim-devel
    - libkleo-devel
    - libksieve-devel
    - mailcommon-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - prison-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
