name       : kdepim-addons
version    : 21.08.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kdepim-addons-21.08.0.tar.xz : c224dce2b422e10ea7d908070549dcf7ce956f546ed440d333ee1bdb7f086e39
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Addons for KDE PIM applications
description: |
    Addons for KDE PIM applications including akregator, kaddressbook, kmail and korganizer.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(libmarkdown)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-import-wizard-devel
    - akonadi-notes-devel
    - calendarsupport-devel
    - eventviews-devel
    - incidenceeditor-devel
    - kaddressbook-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kguiaddons-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitinerary-devel
    - kmailtransport-devel
    - kontactinterface-devel
    - kparts-devel
    - kpkpass-devel
    - ktnef-devel
    - libgravatar-devel
    - libksieve-devel
    - mailcommon-devel
    - mailimporter-devel
    - pimcommon-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
