name       : kdepim-addons
version    : 23.04.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/kdepim-addons-23.04.0.tar.xz : 9fb406498ce57505a7bea5b156fc10cab010f7312c25322aa9dcd1e3614127d5
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Addons for KDE PIM applications
description: |
    Addons for KDE PIM applications including akregator, kaddressbook, kmail and korganizer.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(libmarkdown)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-import-wizard-devel
    - akonadi-notes-devel
    - calendarsupport-devel
    - eventviews-devel
    - incidenceeditor-devel
    - kaddressbook-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kguiaddons-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitinerary-devel
    - kmailtransport-devel
    - kontactinterface-devel
    - kparts-devel
    - kpkpass-devel
    - ktextaddons-devel
    - ktnef-devel
    - libgravatar-devel
    - libksieve-devel
    - mailcommon-devel
    - mailimporter-devel
    - pimcommon-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
