name       : kdepim-addons
version    : 22.08.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kdepim-addons-22.08.3.tar.xz : 4e012cb11a1c5f2105f84e95acb094dd8ef7d4a8c35b10fd268f40fba64f8e72
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.kde
summary    : Addons for KDE PIM applications
description: |
    Addons for KDE PIM applications including akregator, kaddressbook, kmail and korganizer.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(libmarkdown)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-import-wizard-devel
    - akonadi-notes-devel
    - calendarsupport-devel
    - eventviews-devel
    - incidenceeditor-devel
    - kaddressbook-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kguiaddons-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitinerary-devel
    - kmailtransport-devel
    - kontactinterface-devel
    - kparts-devel
    - kpkpass-devel
    - ktnef-devel
    - libgravatar-devel
    - libksieve-devel
    - mailcommon-devel
    - mailimporter-devel
    - pimcommon-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
